export interface AchievementDef {
  key: string
  title: string
  description: string
  category: 'ONBOARDING' | 'MISSIONS' | 'REFERRALS' | 'SOCIAL' | 'SCORE' | 'LEVEL' | 'SPECIAL'
  tier: 'BRONZE' | 'SILVER' | 'GOLD' | 'PLATINUM' | 'LEGENDARY'
  pointReward: number
  scoreReward: number
  condition: {
    type: 'REFERRAL_COUNT' | 'MISSION_COUNT' | 'SCORE_THRESHOLD' | 'LEVEL_REACHED' | 'SOCIAL_COUNT' | 'ONE_TIME'
    threshold?: number
    source?: string
  }
}

export const ACHIEVEMENT_DEFINITIONS: AchievementDef[] = [
  // ─── Onboarding ────────────────────────────────────────────────────────────
  {
    key: 'node_activated',
    title: 'Online',
    description: 'Activate your node for the first time',
    category: 'ONBOARDING',
    tier: 'BRONZE',
    pointReward: 100,
    scoreReward: 200,
    condition: { type: 'ONE_TIME', source: 'NODE_ACTIVATION' },
  },
  {
    key: 'first_check_in',
    title: 'Present',
    description: 'Complete your first daily check-in',
    category: 'ONBOARDING',
    tier: 'BRONZE',
    pointReward: 50,
    scoreReward: 50,
    condition: { type: 'ONE_TIME', source: 'CHECK_IN' },
  },

  // ─── Missions ──────────────────────────────────────────────────────────────
  {
    key: 'first_mission',
    title: 'First Steps',
    description: 'Complete your first mission',
    category: 'MISSIONS',
    tier: 'BRONZE',
    pointReward: 100,
    scoreReward: 100,
    condition: { type: 'MISSION_COUNT', threshold: 1 },
  },
  {
    key: 'missions_5',
    title: 'Getting Started',
    description: 'Complete 5 missions',
    category: 'MISSIONS',
    tier: 'BRONZE',
    pointReward: 200,
    scoreReward: 200,
    condition: { type: 'MISSION_COUNT', threshold: 5 },
  },
  {
    key: 'missions_10',
    title: 'Mission Ready',
    description: 'Complete 10 missions',
    category: 'MISSIONS',
    tier: 'SILVER',
    pointReward: 500,
    scoreReward: 500,
    condition: { type: 'MISSION_COUNT', threshold: 10 },
  },
  {
    key: 'missions_25',
    title: 'Mission Veteran',
    description: 'Complete 25 missions',
    category: 'MISSIONS',
    tier: 'SILVER',
    pointReward: 1_000,
    scoreReward: 1_000,
    condition: { type: 'MISSION_COUNT', threshold: 25 },
  },
  {
    key: 'missions_50',
    title: 'Mission Expert',
    description: 'Complete 50 missions',
    category: 'MISSIONS',
    tier: 'GOLD',
    pointReward: 2_500,
    scoreReward: 2_500,
    condition: { type: 'MISSION_COUNT', threshold: 50 },
  },
  {
    key: 'missions_100',
    title: 'Mission Master',
    description: 'Complete 100 missions',
    category: 'MISSIONS',
    tier: 'GOLD',
    pointReward: 5_000,
    scoreReward: 5_000,
    condition: { type: 'MISSION_COUNT', threshold: 100 },
  },
  {
    key: 'missions_500',
    title: 'Mission Legend',
    description: 'Complete 500 missions',
    category: 'MISSIONS',
    tier: 'LEGENDARY',
    pointReward: 25_000,
    scoreReward: 25_000,
    condition: { type: 'MISSION_COUNT', threshold: 500 },
  },

  // ─── Referrals ─────────────────────────────────────────────────────────────
  {
    key: 'referrals_1',
    title: 'Recruiter',
    description: 'Refer your first user',
    category: 'REFERRALS',
    tier: 'BRONZE',
    pointReward: 200,
    scoreReward: 100,
    condition: { type: 'REFERRAL_COUNT', threshold: 1 },
  },
  {
    key: 'referrals_5',
    title: 'Connector',
    description: 'Refer 5 users',
    category: 'REFERRALS',
    tier: 'SILVER',
    pointReward: 500,
    scoreReward: 500,
    condition: { type: 'REFERRAL_COUNT', threshold: 5 },
  },
  {
    key: 'referrals_10',
    title: 'Networker',
    description: 'Refer 10 users',
    category: 'REFERRALS',
    tier: 'SILVER',
    pointReward: 1_000,
    scoreReward: 1_000,
    condition: { type: 'REFERRAL_COUNT', threshold: 10 },
  },
  {
    key: 'referrals_25',
    title: 'Influencer',
    description: 'Refer 25 users',
    category: 'REFERRALS',
    tier: 'GOLD',
    pointReward: 2_500,
    scoreReward: 2_500,
    condition: { type: 'REFERRAL_COUNT', threshold: 25 },
  },
  {
    key: 'referrals_50',
    title: 'Ambassador',
    description: 'Refer 50 users',
    category: 'REFERRALS',
    tier: 'GOLD',
    pointReward: 5_000,
    scoreReward: 5_000,
    condition: { type: 'REFERRAL_COUNT', threshold: 50 },
  },
  {
    key: 'referrals_100',
    title: 'Growth Engine',
    description: 'Refer 100 users',
    category: 'REFERRALS',
    tier: 'PLATINUM',
    pointReward: 10_000,
    scoreReward: 10_000,
    condition: { type: 'REFERRAL_COUNT', threshold: 100 },
  },
  {
    key: 'referrals_250',
    title: 'Community Builder',
    description: 'Refer 250 users',
    category: 'REFERRALS',
    tier: 'PLATINUM',
    pointReward: 25_000,
    scoreReward: 25_000,
    condition: { type: 'REFERRAL_COUNT', threshold: 250 },
  },
  {
    key: 'referrals_500',
    title: 'Ecosystem Pillar',
    description: 'Refer 500 users',
    category: 'REFERRALS',
    tier: 'LEGENDARY',
    pointReward: 50_000,
    scoreReward: 50_000,
    condition: { type: 'REFERRAL_COUNT', threshold: 500 },
  },
  {
    key: 'referrals_1000',
    title: 'Genesis Recruiter',
    description: 'Refer 1,000 users — legendary status',
    category: 'REFERRALS',
    tier: 'LEGENDARY',
    pointReward: 100_000,
    scoreReward: 100_000,
    condition: { type: 'REFERRAL_COUNT', threshold: 1000 },
  },

  // ─── Social ────────────────────────────────────────────────────────────────
  {
    key: 'social_first',
    title: 'Connected',
    description: 'Connect your first social account',
    category: 'SOCIAL',
    tier: 'BRONZE',
    pointReward: 100,
    scoreReward: 100,
    condition: { type: 'SOCIAL_COUNT', threshold: 1 },
  },
  {
    key: 'social_all',
    title: 'Fully Linked',
    description: 'Connect all 3 social accounts',
    category: 'SOCIAL',
    tier: 'SILVER',
    pointReward: 500,
    scoreReward: 500,
    condition: { type: 'SOCIAL_COUNT', threshold: 3 },
  },

  // ─── Score Milestones ──────────────────────────────────────────────────────
  {
    key: 'score_1000',
    title: 'Rising',
    description: 'Reach 1,000 Node Score',
    category: 'SCORE',
    tier: 'BRONZE',
    pointReward: 100,
    scoreReward: 0,
    condition: { type: 'SCORE_THRESHOLD', threshold: 1_000 },
  },
  {
    key: 'score_5000',
    title: 'Growing Strong',
    description: 'Reach 5,000 Node Score',
    category: 'SCORE',
    tier: 'SILVER',
    pointReward: 300,
    scoreReward: 0,
    condition: { type: 'SCORE_THRESHOLD', threshold: 5_000 },
  },
  {
    key: 'score_15000',
    title: 'Guardian Tier',
    description: 'Reach 15,000 Node Score',
    category: 'SCORE',
    tier: 'SILVER',
    pointReward: 500,
    scoreReward: 0,
    condition: { type: 'SCORE_THRESHOLD', threshold: 15_000 },
  },
  {
    key: 'score_50000',
    title: 'Architect Tier',
    description: 'Reach 50,000 Node Score',
    category: 'SCORE',
    tier: 'GOLD',
    pointReward: 2_000,
    scoreReward: 0,
    condition: { type: 'SCORE_THRESHOLD', threshold: 50_000 },
  },
  {
    key: 'score_100000',
    title: 'Sentinel Tier',
    description: 'Reach 100,000 Node Score',
    category: 'SCORE',
    tier: 'GOLD',
    pointReward: 5_000,
    scoreReward: 0,
    condition: { type: 'SCORE_THRESHOLD', threshold: 100_000 },
  },
  {
    key: 'score_1000000',
    title: 'Millionaire Node',
    description: 'Reach 1,000,000 Node Score',
    category: 'SCORE',
    tier: 'LEGENDARY',
    pointReward: 50_000,
    scoreReward: 0,
    condition: { type: 'SCORE_THRESHOLD', threshold: 1_000_000 },
  },

  // ─── Level Milestones ──────────────────────────────────────────────────────
  {
    key: 'level_5',
    title: 'Architect Node',
    description: 'Reach Level 5 — Architect',
    category: 'LEVEL',
    tier: 'SILVER',
    pointReward: 1_000,
    scoreReward: 0,
    condition: { type: 'LEVEL_REACHED', threshold: 5 },
  },
  {
    key: 'level_10',
    title: 'Commander Node',
    description: 'Reach Level 10 — Commander',
    category: 'LEVEL',
    tier: 'GOLD',
    pointReward: 5_000,
    scoreReward: 0,
    condition: { type: 'LEVEL_REACHED', threshold: 10 },
  },
  {
    key: 'level_15',
    title: 'Mythic Node',
    description: 'Reach Level 15 — Mythic',
    category: 'LEVEL',
    tier: 'PLATINUM',
    pointReward: 20_000,
    scoreReward: 0,
    condition: { type: 'LEVEL_REACHED', threshold: 15 },
  },
  {
    key: 'level_20',
    title: 'Genesis Node',
    description: 'Reach Level 20 — Genesis',
    category: 'LEVEL',
    tier: 'LEGENDARY',
    pointReward: 100_000,
    scoreReward: 0,
    condition: { type: 'LEVEL_REACHED', threshold: 20 },
  },
]
